name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
    - run: poetry config pypi-token.testpypi ${{ secrets.PYPI_TEST_TOKEN }}
    - name: Publish package
      run: poetry publish --build -r testpypi
