name: Publish to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync --all-extras --all-groups
    - name: Build
      run: uv build
    - name: Publish
      run: uv publish --token "${{ secrets.PYPI_TOKEN }}"
